[platformio]
default_envs = wio_l1_oled, pager_sx1262

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    jgromes/RadioLib@7.1.2
    adafruit/Adafruit GFX Library@1.12.6
build_unflags = -std=gnu++11
build_flags = -I include -std=gnu++17

[env:wio_l1_oled]
platform = nordicnrf52@11.0.0
board = wio_l1_oled
board_build.ldscript = variants/wio_l1_oled/nrf52840_s140_v7.ld
extra_scripts = pre:scripts/wio_build.py
build_flags = ${env.build_flags} -D DEVICE_WIO
lib_deps =
    ${env.lib_deps}
    adafruit/Adafruit SSD1306@2.5.15

[pager]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-s3-devkitc-1
board_build.variant = lilygo_tlora_pager
; T-LoRa Pager has quad SPI PSRAM, not octal PSRAM.
board_build.arduino.memory_type = qio_qspi
board_build.psram_type = qspi
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
build_flags =
    ${env.build_flags}
    -D DEVICE_PAGER
    -D ARDUINO_T_LORA_PAGER
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D LV_CONF_SKIP
    -D LV_USE_STDLIB_MALLOC=LV_STDLIB_CUSTOM
lib_deps =
    ${env.lib_deps}
    LilyGoLib=symlink://vendor/LilyGoLib
    adafruit/Adafruit TCA8418@1.0.2
    mikalhart/TinyGPSPlus@1.0.3
    https://github.com/lewisxhe/ST25R3916-fork.git#0c8e00f49d12881d1cff6d6f0879b90ce7ed4033
    https://github.com/lewisxhe/NFC-RFAL-fork.git#7bde4587ea44c36c178a43d083d7a7345c1e4cfe

[env:pager_sx1262]
extends = pager
build_flags = ${pager.build_flags} -D ARDUINO_LILYGO_LORA_SX1262

[env:pager_lr1121]
extends = pager
build_flags = ${pager.build_flags} -D ARDUINO_LILYGO_LORA_LR1121
